server:
  port: 9090
  
spring:
  profiles:
    active: native, git
  application:
    name: config-server-cloud
  cloud:
    config:
      server:
        native:
          searchLocations: file:///${user.home}/config-repo
        git:
          uri: https://github.com/guilhermegarcia86/ConfigData